#!/bin/bash

t=0.5
c="ff ff ff"
c2="00 00 00"
while [ $# -gt 0 ]
do
  case "$1"
  in
    -t)
      t="$2"; shift 2
    ;;
    -c)
      c="$2"; shift 2
    ;;
    -c2)
      c2="$2"; shift 2
    ;;
    *)
      break
    ;;
  esac
done
keys="$*"

while true
do
  netcat localhost 12345 <<END
set $c $keys
update 
wait $t
set $c2 $keys
update 
wait $t
END
done 

