#!/bin/sh
set -e

netcat localhost 12345 <<EOF

set ff ff ff TAB
update
wait 0.75
set ff ff ff Q
update
wait 0.75
set ff ff ff W
update
wait 0.75
set ff ff ff E
update
wait 0.75

set 00 00 00 TAB
update
wait 0.75
set 00 00 00 q
update
wait 0.75
set 00 00 00 w
update
wait 0.75
set 00 00 00 e
update
wait 0.75

set ff 00 00 TAB
update
wait 0.75
set ff 00 00 Q
update
wait 0.75
set ff 00 00 W
update
wait 0.75
set ff 00 00 E
update
wait 0.75

set 00 ff 00 TAB
update
wait 0.75
set 00 ff 00 Q
update
wait 0.75
set 00 ff 00 W
update
wait 0.75
set 00 ff 00 E
update
wait 0.75

set 00 00 ff TAB
update
wait 0.75
set 00 00 ff Q
update
wait 0.75
set 00 00 ff W
update
wait 0.75
set 00 00 ff E
update
wait 0.75

set 00 00 00 TAB
update
wait 0.75
set 00 00 00 Q
update
wait 0.75
set 00 00 00 W
update
wait 0.75
set 00 00 00 E
update
wait 0.75

EOF

exit 0
