#!/bin/sh
set -e

t=0.1
black="00 00 00"
white="ff ff ff"

keys="TAB CAPS LSHIFT LCTRL LSTART LALT RALT RSTART MENU RCTRL RSHIFT ENTER BACKSPACE DEL HOME PUP PDOWN END UP LEFT DOWN RIGHT"
(
for key in $keys
do
  cat <<EOF
set $white $key
update
wait $t
EOF
done 

for key in $keys
do
  cat <<EOF
set $black $key
update
wait $t
EOF
done 

) | netcat localhost 12345

exit 0
