#!/bin/sh
set -e

netcat localhost 12345 <<EOF

set ff ff ff ~
update
wait 0.5
set ff ff ff 1
update
wait 0.5
set ff ff ff 2
update
wait 0.5
set ff ff ff 3
update
wait 0.5

set 0 0 0 #0
update
wait 0.5
set 0 0 0 1
update
wait 0.5
set 0 0 0 2
update
wait 0.5
set 0 0 0 #
update
wait 0.5

set ff 00 00 ~
update
wait 0.5
set ff 00 00 1
update
wait 0.5
set ff 00 00 2
update
wait 0.5
set ff 00 00 3
update
wait 0.5

set 00 ff 00 ~
update
wait 0.5
set 00 ff 00 1
update
wait 0.5
set 00 ff 00 2
update
wait 0.5
set 00 ff 00 3
update
wait 0.5

set 00 00 ff ~
update
wait 0.5
set 00 00 ff 1
update
wait 0.5
set 00 00 ff 2
update
wait 0.5
set 00 00 ff 3
update
wait 0.5

set 00 00 00 #0
update
wait 0.5
set 00 00 00 1
update
wait 0.5
set 00 00 00 2
update
wait 0.5
set 00 00 00 3
update
wait 0.5

EOF

exit 0
