#!/bin/bash
# Monitors for synergy connections.
# Lights first two keys based on the number of synergy client connections.
# set -x 

while true
do
  connections="$(netstat -nap 2>/dev/null | grep synergys | grep ESTABLISHED | wc -l)"
  # echo "connections='$connections'" >&2
  case $connections
  in
    0)
      cat <<EOF
s 00 00 00 0 1 
u
EOF
    ;;
    1)
      cat <<EOF
s 00 00 00 0 1 
s 00 00 ff 0
u
EOF
    ;;
    2)
      cat <<EOF
s 00 00 00 0 1 
s 00 00 ff 0 1
u
EOF
    ;;
  esac 
  sleep 10
done | netcat localhost 12345

