#!/usr/bin/env bash
set -x

pids=
trap 'set -x; kill -9 $pids 2>/dev/null' EXIT

sudo ./luxeed --server & pids+="$! "

for t in ./luxeed_t{1,2,3,4}
do
  (while true; do "$t"; sleep 1; done) &
  pids+="$! "
done

